In [2]:
import xml.etree.ElementTree as Xet 
import pandas as pd

In [61]:
import csv
import xml.etree.ElementTree as ET

def xml_to_csv(xml_file, csv_file):  
    tree = ET.parse(xml_file)
    root = tree.getroot()

    with open(csv_file, 'w', newline='', encoding='utf-8') as csvfile:
        csv_writer = csv.writer(csvfile)
       
        csv_writer.writerow(['Id','PostId','VotetypeId','CreationDate'])

        for row in root.findall('row'):
            row_data = [
                row.get('Id'),
                row.get('PostId'),
                row.get('VotetypeId'),
                row.get('CreationDate')                        
            ]
            csv_writer.writerow(row_data)

if __name__ == "__main__":
    xml_file_path = 'G:\\Anitha\\stackexchange\\Votes.xml'  
    csv_file_path = 'G:\\Anitha\\stackexchange\\Votes.csv'      

    xml_to_csv(xml_file_path, csv_file_path)

In [63]:
xml_to_csv

In [11]:
badges=pd.read_csv('G:\\Anitha\\stackexchange\\Badges.csv')
comments=pd.read_csv('G:\\Anitha\\stackexchange\\Comments.csv')
votes=pd.read_csv('G:\\Anitha\\stackexchange\\Votes.csv')
users=pd.read_csv('G:\\Anitha\\stackexchange\\Users.csv')
posts=pd.read_csv('G:\\Anitha\\stackexchange\\Posts.csv')
tags=pd.read_csv('G:\\Anitha\\stackexchange\\Tags.csv')
postlinks=pd.read_csv('G:\\Anitha\\stackexchange\\PostLinks.csv')
posthistory=pd.read_csv('G:\\Anitha\\stackexchange\\PostHistory.csv')

In [20]:
tags.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 354 entries, 0 to 353
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             354 non-null    int64
 1   TagName        354 non-null    object
 2   ExcerptPostId  334 non-null    float64
 3   WikiPostId     334 non-null    float64
dtypes: float64(2), int64(1), object(1)
memory usage: 11.2+ KB

In [8]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22394 entries, 0 to 22393
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Id              22394 non-null  int64
 1   Reputation      22394 non-null  int64
 2   CreationDate    22394 non-null  object
 3   DisplayName     22392 non-null  object
 4   LastAccessDate  22394 non-null  object
 5   WebsiteUrl      5919 non-null   object
 6   Location        8604 non-null   object
 7   Views           22394 non-null  int64
 8   UpVotes         22394 non-null  int64
 9   DownVotes       22394 non-null  int64
 10  AccountId       22394 non-null  int64
dtypes: int64(6), object(5)
memory usage: 1.9+ MB

In [22]:
tags.head(5)

   Id      TagName  ExcerptPostId  WikiPostId
0   2         visa         7686.0      7685.0
1   4   job-search         2147.0      2146.0
2   5     journals         3231.0      3230.0
3   7  engineering        20748.0     20747.0
4   9    copyright         7564.0      7563.0

In [23]:
posts.head(10)

,Id,PostTypeId,AcceptedAnswerId,CreationDate,Score,ViewCount,Body,OwnerUserId,LastEditorUserId,LastEditDate,LastActivityDate,Title,AnswerCount,CommentCount,FavoriteCount
0,1,1,180.0,2012-02-14T20:23:40.127,12,198.0,<p>As from title. What kind of visa class do I...,5.0,2700.0,2013-10-30T09:14:11.633,2013-10-30T09:14:11.633,What kind of Visa is required to work in Acade...,1.0,1,1.0
1,2,1,246.0,2012-02-14T20:26:22.683,7,386.0,<p>Which online resources are available for jo...,5.0,15723.0,2014-09-18T13:02:01.180,2014-09-18T13:02:01.180,"As a computational chemist, which online resou...",2.0,2,NaN
2,3,1,6.0,2012-02-14T20:27:41.980,31,1659.0,<p>As from title. Not all journals provide the...,5.0,1580.0,2012-10-04T15:22:37.497,2013-09-10T19:58:02.267,Where can I find the Impact Factor for a given...,4.0,0,8.0
3,4,1,145.0,2012-02-14T20:29:04.737,9,200.0,<p>I have seen many engineering departments wa...,18.0,15723.0,2014-09-18T13:02:31.710,2014-09-18T13:02:31.710,"In U.S., why do many engineering departments c...",2.0,0,1.0
4,5,1,9.0,2012-02-14T20:30:26.703,23,525.0,"<p>What is the h-index, and how does it work ?...",5.0,1580.0,2012-10-04T15:25:09.833,2012-10-04T15:25:09.833,What is the h-index exactly and how does it work?,1.0,1,1.0
5,6,2,NaN,2012-02-14T20:30:29.917,19,NaN,<p>If your institution has a subscription to J...,18.0,NaN,NaN,2012-02-14T20:30:29.917,NaN,NaN,2,NaN
6,7,1,20.0,2012-02-14T20:32:12.333,61,4299.0,"<p>If I publish a pre-print paper on arXiv, ho...",5.0,15723.0,2014-09-18T13:17:40.567,2014-09-18T13:17:40.567,Does publishing a paper on arXiv prevent me fr...,5.0,1,9.0
7,8,1,26.0,2012-02-14T20:34:32.130,17,444.0,<p>An increasing number of funding organizatio...,12.0,15723.0,2014-09-10T13:26:21.987,2014-09-10T13:26:21.987,What journals do not allow open access to publ...,2.0,2,2.0
8,9,2,NaN,2012-02-14T20:39:18.063,23,NaN,<p>The h-index is a measure of the impact of s...,12.0,NaN,NaN,2012-02-14T20:39:18.063,NaN,NaN,3,NaN
9,10,2,NaN,2012-02-14T20:39:46.567,28,NaN,"<p>Not necessarily, but this is to be dealt wi...",26.0,26.0,2013-03-12T03:34:06.693,2013-03-12T03:34:06.693,NaN,NaN,0,NaN

In [24]:
import os

In [26]:
os.p

AttributeError: module 'os' has no attribute 'cwd'